"""first migration

Revision ID: 3b4c664d02af
Revises: 
Create Date: 2024-09-19 20:33:50.080879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b4c664d02af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_listing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image_link', sa.String(length=255), nullable=True),
    sa.Column('ingredients', sa.String(length=100), nullable=True),
    sa.Column('instructions', sa.String(length=100), nullable=True),
    sa.Column('dietary_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('recipe_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commentary', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('recipe_listing_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_listing_id'], ['recipe_listing.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_reviews')
    op.drop_table('users')
    op.drop_table('recipe_listing')
    # ### end Alembic commands ###
